/* eslint-disable max-len */
import React from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/landing_page/header';
import Footer from '../components/landing_page/footer';

import MainContent from '../components/landing_page/main_content';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        links={[
          {
            link: '/login',
            label: 'Login',
          },
          {
            link: '',
            label: 'Pricing',
          },
          {
            link: '',
            label: 'About',
          },
        ]}
      />

      <MainContent />

      <Footer
        links={[
          {
            link: '#',
            label: 'Contact',
          },
          {
            link: '#',
            label: 'Privacy',
          },
          {
            link: '#',
            label: 'Blog',
          },
          {
            link: '#',
            label: 'Store',
          },
          {
            link: '#',
            label: 'Careers',
          },
        ]}
      />
    </div>
  );
};

export default Home;
