/* eslint-disable max-len */
import React from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header/header';
import Footer from '../components/Footer/footer';
import { Container, createStyles } from '@mantine/core';
import { Image } from '@mantine/core';
const useStyles = createStyles((theme) => {
  return {
    banner: {
      border: '1px solid red',
      display: 'flex',
      flexDirection: theme.fn.largerThan('md') ? 'row' : 'column',
    },
    content: {
      width: '75%',
      border: '1px solid black',
    },
    bannerImage: {},
  };
});
const Home: NextPage = () => {
  const imageUrl =
    'https://images.unsplash.com/uploads/141103282695035fa1380/95cdfeef?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1730&q=80';

  const { classes } = useStyles();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        links={[
          {
            link: 'google.com',
            label: 'Features',
          },
          {
            link: '',
            label: 'Pricing',
          },
          {
            link: '',
            label: 'About',
          },
        ]}
      />

      <Container className={classes.banner}>
        {/* Left */}
        <Container className={classes.content}>
          Get yourself a job with
          <strong>Plairsty</strong>
        </Container>
        {/* Right */}
        <Image
          radius="md"
          src={imageUrl}
          alt="Random unsplash image"
          className={classes.bannerImage}
        />
      </Container>

      <Footer
        links={[
          {
            link: '#',
            label: 'Contact',
          },
          {
            link: '#',
            label: 'Privacy',
          },
          {
            link: '#',
            label: 'Blog',
          },
          {
            link: '#',
            label: 'Store',
          },
          {
            link: '#',
            label: 'Careers',
          },
        ]}
      />
      <h1>About</h1>
    </div>
  );
};

export default Home;
